spring:
  datasource:
    url: jdbc:postgresql://${PGPORT}:{PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop

